# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  database: obitmvp_dev
  username: root
  password: obitmvp 
  host: localhost
test:
  adapter: mysql2
  database: obitmvp_test 
  username: root
  password: obitmvp 
  host: localhost
production:
  adapter: mysql2
  database: obitmvp_prod
  username: root
  password: obitmvp 
  host: localhost

default: &default
  adapter: mysql
  pool: 5
  timeout: 5000

